/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 * Global Trust Authority is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *     http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

pub const HUAWEI_EQUIPMENT_ROOT_CA_PEM: &[u8] = br#"-----BEGIN CERTIFICATE-----
MIICoDCCAgKgAwIBAgIDazWSMAoGCCqGSM49BAMEMDwxDzANBgNVBAoTBkh1YXdl
aTEpMCcGA1UEAxMgSHVhd2VpIEVDQyBBdHRlc3RhdGlvbiBSb290IENBIDEwIBcN
MjQwMzMwMDQ1NDEyWhgPMjA3NDAzMzAwNDU0MTJaMDwxDzANBgNVBAoTBkh1YXdl
aTEpMCcGA1UEAxMgSHVhd2VpIEVDQyBBdHRlc3RhdGlvbiBSb290IENBIDEwgZsw
EAYHKoZIzj0CAQYFK4EEACMDgYYABAGPYVYcrvY5RGQiKtogIiYGWJRs/1Dwr9hJ
5zsc9zQaceMX0JANd8p2miTRJbri1iy1i0E0kPpQyLF13t+1tDwlqgG5TN8lwaCn
1E8AiOtZ/EP5L8Umpgpl89kcRv937Jkv2ivUznfJzgdNtZV1zDkSR0qvoPPGF5FJ
UVCQDaz9C1D4RKOBrTCBqjAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB
/zBHBgNVHSAEQDA+MDwGDCsGAQQBj1uBSQEEBzAsMCoGCCsGAQUFBwIBFh5odHRw
czovL3N1cHBvcnQuaHVhd2VpLmNvbS9wa2kwHQYDVR0OBBYEFKmN+LpfDw9KWfN5
oqWa4knCX5+kMB8GA1UdIwQYMBaAFKmN+LpfDw9KWfN5oqWa4knCX5+kMAoGCCqG
SM49BAMEA4GLADCBhwJCAS2rcB3imVKaunb/t+pq2hstjHAl5vqP2rt+0fjN14Cq
csMCl2u2oHznPTSaeN1CK5ObKROxkpdwsYVISiGDu3eJAkFFqY25Q86PK3sBro1V
MUnKR0sZvKRQK1Uvr7K/kDqQrW+nSgfdSX/n4ZmEYyozXyP3DQYYZwUNzfqk0ZHW
rXR7Mg==
-----END CERTIFICATE-----
"#;

pub const HUAWEI_PRODUCT_CA_PEM: &[u8] = br#"-----BEGIN CERTIFICATE-----
MIIDEzCCAnWgAwIBAgIREjwNmamCifcSzIM4CHEAvYEwCgYIKoZIzj0EAwQwPDEP
MA0GA1UEChMGSHVhd2VpMSkwJwYDVQQDEyBIdWF3ZWkgRUNDIEF0dGVzdGF0aW9u
IFJvb3QgQ0EgMTAgFw0yNDA5MTExMDEwNDBaGA8yMDc0MDMyODEwMTA0MFowRjEL
MAkGA1UEBhMCQ04xDzANBgNVBAoTBkh1YXdlaTEmMCQGA1UEAxMdSHVhd2VpIENv
bXB1dGluZyBFQ0MgQ0NBIENBIDEwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAB9
eCf3EORVOECC4DFgOgdvttpC5nJ1/Yol0ErwQVhmP4DIMOnqHUVpzR/VXwblKVkH
Iu3LJ3fzBU0E+AQcdmMu/AG1ynEzkPvI7zhlkRVVX4nS7YoGndUYw86gsJdSfVn1
+ESZm1u+o9jMZIxZ4zLYEa+BzOYNOtRDLDGSLD06kdrygaOCAQcwggEDMB8GA1Ud
IwQYMBaAFKmN+LpfDw9KWfN5oqWa4knCX5+kMB0GA1UdDgQWBBSIMTazZebllUGe
vBwRPBtf4zdi7TASBgNVHRMBAf8ECDAGAQH/AgEAMEcGA1UdIARAMD4wPAYMKwYB
BAGPW4FJAQQHMCwwKgYIKwYBBQUHAgEWHmh0dHBzOi8vc3VwcG9ydC5odWF3ZWku
Y29tL3BraTAOBgNVHQ8BAf8EBAMCAQYwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
L3N1cHBvcnQuaHVhd2VpLmNvbS9zdXBwb3J0L3BraS9lY2NfYXR0ZW5zdGF0aW9u
X3Jvb3RfY3JsLmNybDAKBggqhkjOPQQDBAOBiwAwgYcCQgHaDPvAEUAVeRVo4Mn+
UoVlcPtwa1TWDHYInzHQ9leL7PVTZLnCg6vKSuo0G3I9Gz/YtOz+ylTpzGekqJf/
00JKcQJBep4ZMYxe+KmplOj/uqoUvy97sQ77jFe+kQvlXkbt7QidjnTlT2itS6CS
HvWyRwqIjVLItwhea7FvwDhvUgyLdTc=
-----END CERTIFICATE-----
"#;
