[package]
name = "ratls-sample"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cca-server"
path = "src/bin/cca-server.rs"

[[bin]]
name = "cca-client"
path = "src/bin/cca-client.rs"

[dependencies]
ratls-api = { path = "../ratls-api" }
clap = { version = "4", features = ["derive"] }
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
