#ifndef TPM_DRIVER_V2_INTERFACE_H
#define TPM_DRIVER_V2_INTERFACE_H

#define TPM_ACCESS_VALID 0x80U
#define TPM_ACCESS_ACTIVE_LOCALITY 0x20U
#define TPM_ACCESS_REQUEST_USE 0x02U

#define TPM_STS_VALID 0x80U
#define TPM_STS_COMMAND_READY 0x40U
#define TPM_STS_TPMGO 0x20U
#define TPM_STS_DATA_AVAIL 0x10U
#define TPM_STS_DATA_EXPECT 0x08U

#define TPM2_TIMEOUT_A 750000U
#define TPM2_DURATION_LONG_LONG 300000000U

#define TPM_SPI_DELAY 1U
#define TPM_ACK_TRY_TIMES 10000U

#define TPM_WAIT_LOOP 2000U
#define TPM_CMD_READY_WAIT_TIME 1000U
#define TPM_DELAY_TIME 1U
#define TPM_ACCESS_TRY_TIME 10U
#define MAX_SPI_FRAMESIZE 64U

#define TPM_ID_ADDR_0 0xD40F00U
#define TPM_CMD_HEADER_SIZE 10U
#define TPM_MAX_LOCALITY 5U

#define TPM_ACCESS_ACTIVED_MASK (TPM_ACCESS_VALID | TPM_ACCESS_ACTIVE_LOCALITY)
#define IS_TPM_ACCESS_ACTIVED(x) (((x) & TPM_ACCESS_ACTIVED_MASK) == TPM_ACCESS_ACTIVED_MASK)

#define TPM_ACCESS(x) (((x) << 12U) | 0xD40000U)
#define TPM_SYS_1(x) (((x) << 12U) | 0xD40018U)

#define TPM_DATA_FIFO_1(x) (((x) << 12U) | 0xD40024U)

#endif
